name: learn-github-actions
run-name: ${{ github.actor }} upload to Google Cloud Storage
on: [push]
jobs:
  google-cloud-storage-upload:
    permisions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: 'pages/immersive'
          destination: 'github-actions-gcs-test-qa/immersive'